### ISSUE TITLE
Clarify Spec for Date

### ISSUE THREAD

**Issue by Weltraumschaf** [devsecopsmaturitymodel/metricCA#1]
Just stumbled upon this [line in the ADR](https://github.com/devsecopsmaturitymodel/metricCA/blob/840f1bd3e48deb83e6ac03c563ca84b18053054a/docs/ADR/yaml.md?plain=1#L31) which specifies the date format:

> Date format is `Year-Month-Day`.

From my experience it would lead to less misinterpretation, when the spec is more precise, e.g.

> Date is in ISO format `YYYY-MM-DD` to support order-by-date with lexicographic ordering of file names.

**Comment by wurstbrot** [comment]
thanks,  done
