### ISSUE TITLE
Clarification of File Name Format

### ISSUE THREAD

**Issue by Weltraumschaf** [devsecopsmaturitymodel/metricCA#2]
In this [line of the ADR](https://github.com/devsecopsmaturitymodel/metricCA/blob/840f1bd3e48deb83e6ac03c563ca84b18053054a/docs/ADR/yaml.md?plain=1#L161) the file name format is specified as:

> Application-based yamls have the prefix `application`, a second application for the team rebels could be named like `teamXYZ/applicationStarDestroyer.yaml`.

If the file name will be used in the future for other purposes (e.g. derive the application name from it or such), then it may make sense to define a more strict pattern. Thins to consider: What characters will be allowed (imagine an application e.g. named "Foo++"). Does camel case has a special meaning? E.g. for word splitting? In general this my lead to problems and a dash (`-`) to separate words is a better option. If the filename does not matter in any way, then this should be noted and also documented as a consequence of this decission.

**Comment by wurstbrot** [comment]
Is it better now?
